spring:
  application:
    name: "user-service"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
      timeout: 5s
      connect-timeout: 5s
      repositories:
        enabled: false

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  jwt:
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    private-key: ${JWT_SECRET}
    access-expiration-ms: ${JWT_ACCESS_EXPIRATION} # 30분
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: never

springdoc:
  use-fqn: true

server:
  port: ${SERVER_PORT}

service:
  product:
    url: ${PRODUCT_SERVICE_URL}
  order:
    url: ${ORDER_SERVICE_URL}
  payment:
    url: ${PAYMENT_SERVICE_URL}
