apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  # Database
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"

  # Redis
  REDIS_PASSWORD: "${REDIS_PASSWORD}"

  # JWT
  JWT_SECRET: "${JWT_SECRET}"
